# Generated by Django 5.1 on 2025-01-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Micronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('V', 'Vitamin'), ('M', 'Mineral'), ('TrE', 'Trace element'), ('Ph', 'Phytonutrient'), ('O', 'Other')], default='O', max_length=3)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('other_names', models.CharField(blank=True, max_length=800)),
                ('supplement_sources', models.CharField(blank=True, max_length=800)),
                ('contraindications', models.CharField(blank=True, max_length=800)),
                ('cofactors', models.CharField(blank=True, max_length=800)),
                ('benefits', models.CharField(max_length=800)),
                ('toxicity_symptoms', models.CharField(max_length=800)),
                ('dosage_unit', models.CharField(max_length=200)),
                ('upper_limit', models.IntegerField(blank=True, null=True)),
                ('therapeutic_dose', models.IntegerField(blank=True, null=True)),
                ('rdi', models.IntegerField(blank=True, null=True)),
                ('est_av_req', models.IntegerField(blank=True, null=True)),
                ('adequate_intake', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=800)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_nut_feedback', to=settings.AUTH_USER_MODEL)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_feedback', to='micronutrients.micronutrient')),
            ],
        ),
    ]
