# Generated by Django 5.1 on 2025-01-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micronutrients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='micronutrient',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='micronutrient',
            name='other_names',
        ),
        migrations.AddField(
            model_name='micronutrient',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='micronutrient',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='micronutrient',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='nutrientfeedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='AlternativeNutrientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('associated_nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_nutrient_names', to='micronutrients.micronutrient')),
            ],
        ),
    ]
