# Generated by Django 5.1 on 2025-01-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholefood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('other_names', models.CharField(blank=True, max_length=800)),
                ('image', models.URLField()),
                ('serving_size_grams', models.IntegerField()),
                ('energy_per_serve_kj', models.IntegerField()),
                ('protein_per_serve', models.IntegerField()),
                ('carbs_per_serve', models.IntegerField()),
                ('fat_per_serve', models.IntegerField()),
                ('is_archived', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholefoodFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=800)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_wf_feedback', to=settings.AUTH_USER_MODEL)),
                ('wholefood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholefood_feedback', to='wholefoods.wholefood')),
            ],
        ),
    ]
