# Generated by Django 5.1 on 2025-01-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholefoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholefood',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='wholefood',
            name='other_names',
        ),
        migrations.AddField(
            model_name='wholefood',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholefood',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='wholefood',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wholefoodfeedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='AlternativeWholefoodName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('associated_wholefood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_wholefood_names', to='wholefoods.wholefood')),
            ],
        ),
    ]
